#!/usr/bin/env bash
sudo pacman -S yay
yay -S nvim-drop-in python-neovim  python-pipx  kitty compton dunst
i3-scrot i3lock-fancy-rapid polkit-gnome  xss-lock rofi ttf-iosevka-ss07 ttf-iosevka-term-ss07
ttf-nerd-fonts-symbols fzf ripgrep youtube-dl  
pipx install python-language-server
pipx  inject python-language-server pyls-black pyls-isort pyflakes rope

 ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

