#!/usr/bin/env bash
sudo pacman -S yay
yay
yay -S  rofi nvim-drop-in python-neovim kitty compton dunst\
bsdwm sxhkd dashbinsh i3-scrot i3lock-fancy-rapid\
polkit-gnome xss-lock rofi ttf-iosevka-ss07 ttf-iosevka-term-ss07\
ttf-nerd-fonts-symbols  fzf ripgrep youtube-dl\
python-pipx mpv firefox-developer-edition telegram-desktop  network-manager-applet\
blueman git-lfs direnv git-hub git-delta-bin

sudo chsh -s /usr/bin/fish

pipx install python-language-server
pipx inject python-language-server pyls-black pyls-isort pyflakes rope
