[theme] 
# name = "gruvbox-dark"
name      = "plain"

[theme.overrides]
separator = ''
idle_bg   = '#1f222d'
good_bg   = '#1f222d'
[icons]
# name      = "awesome"
name      = "awesome"

[[block]]
block     = "focused_window"
max_width = 50

[[block]]
block     = "battery"
upower    = true
format    = "{percentage}% {time}"

[[block]]
block     = "sound"
on_click  = "pavucontrol"


[[block]]
block     = "net"
device    = "wlp3s0"
ssid      = true
# ip = true
speed_up  = false
graph_up  = false
interval  = 5

[[block]]
block     = "time"
interval  = 60
format    = "%a %d/%m %R"
