#!/bin/sh
export SXHKD_SHELL=/usr/bin/dash



bspc config window_gap 12


bspc monitor -d ₁ ₂ ₃ ₄ ₅    

bspc config border_width         3
bspc config focused_border_color  '#abefab'
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle  true
# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a "*browser" desktop='^1'
bspc rule -a "TelegramDesktop" desktop='^4'
# bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled


#Don't run if it's running
run_once(){
   printf "%s\n" "$1"
   pidof $1 || $@ &
}

#Those operation are idempotent
pidof sxhkd && pkill -USR1 -x sxhkd || sxhkd &
~/.config/polybar/launch.sh > /dev/null 2>&1 
pkill compton; compton -b
nitrogen --restore
xset s 60 120
fix_xcursor

run_once pulseaudio --start
run_once xss-lock -n dim-screen.sh -- i3lock-fancy-rapid 5 3
run_once /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
run_once unclutter -b

