#!/usr/bin/sh
export SXHKD_SHELL=/usr/bin/sh
bspc monitor -d ₁ ₂ ₃ ₄ ₅ ₆ ₇ ₈ ₉
bspc config window_gap 3
bspc config border_width         1
bspc config focused_border_color  '#afcfee'
bspc config presel_feedback_color  '#afcfee'
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle  true
bspc config directional_focus_tightness low   #focus cycling include floating windows

# remove all rules first
bspc rule -r '*:*'
# bspc rule -a "Brave-browser" desktop='^1' follow=on
bspc rule -a "*:Navigator" desktop='^1' follow=on
bspc rule -a "TelegramDesktop" desktop='^4' follow=on
# bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a PureRef state=floating
bspc rule -a MEGAsync state=floating
bspc rule -a gmic_qt  follow=on focus=on state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Dragon-drag-and-drop sticky=on

# sometimes it creates a fake window, this way it does not causes issues
bspc rule -a nm-applet state=floating 

run_disowned () {
    nohup "$@" > /dev/null 2>&1 &
}

#Don't run if it's running
run_once () {
    pidof "$(basename $1)" || run_disowned "$@"
}

#Those operation are idempotent

# Reload sxhkd manually cause using USR1 hangs the keyboard frome time to time
pkill sxhkd
run_disowned sxhkd
run_once xsettingsd

xset -b
pkill -9 picom; picom -b

nitrogen --restore

export DEFAULT_NETWORK_INTERFACE=$(ip route | grep '^default' | awk '{print $5}' | head -n1)
pkill -9 polybar
run_disowned polybar top

xset s 300 600
run_once light-locker
# run_once xss-lock -- 'pidof i3lock-fancy-rapid || i3lock-fancy-rapid 5 pixel'
run_once /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
run_once nm-applet
run_once unclutter -b #hide the cursor when not moving it
# run_once easyeffects --gapplication-service
