local ev = loadstring

require("lazy").setup(
    {
        { ft = "fennel", "Olical/aniseed" },
        { event = "BufRead", "tpope/vim-unimpaired" },
        "gpanders/nvim-parinfer",
        { config = true, keys = { { "gc", mode = { "n", "v" } } }, "numToStr/Comment.nvim" },
        { config = function() require [[my.plugins/vim-easy-align]] end, "junegunn/vim-easy-align" },
        { keys = { { "gr", mode = { "n", "v" } } }, "vim-scripts/ReplaceWithRegister" },
        "tpope/vim-repeat",
        { config = ev "require[[my.plugins/switch]]",
            dependencies = { keys = { "<Plug>SpeedDatingFallbackUp", "<Plug>SpeedDatingFallbackDown" },
                "tpope/vim-speeddating" }, "AndrewRadev/switch.vim" },
        { cmd = "EnMasse", "Olical/vim-enmasse" },
        { cmd = { "G" }, event = "BufRead", "tpope/vim-fugitive" },
        { after = "vim-fugitive", "tpope/vim-rhubarb" },
        "tpope/vim-eunuch",
        { ft = "python", "Vimjas/vim-python-pep8-indent" },
        { config = ev "require'colorizer'.setup()", "norcalli/nvim-colorizer.lua" },
        "direnv/direnv.vim",
        { config = ev "require[[my.plugins/nvim-surround]]", "kylechui/nvim-surround" },
        { config = ev "require[[my.plugins/splitjoin]]", keys = { "gS", "gJ" }, "AndrewRadev/splitjoin.vim" },
        { config = ev "require[[my.plugins/gitsigns]]", event = "VimEnter", dependencies = { "nvim-lua/plenary.nvim" },
            "lewis6991/gitsigns.nvim" },
        { config = ev "require[[my.plugins/nvim-lspconfig]]", dependencies = { "simrat39/rust-tools.nvim" },
            "neovim/nvim-lspconfig" },
        { "nvim-treesitter/playground", cmd = "TSPlaygroundToggle" },
        { config = ev "require[[my.plugins/nvim-treesitter]]",
            dependencies = { "nvim-treesitter/nvim-treesitter-textobjects" },
            build = ":TSUpdate",
            "nvim-treesitter/nvim-treesitter" },
        { config = ev "require[[my.plugins/LuaSnip]]", dependencies = { "rafamadriz/friendly-snippets" },
            "L3MON4D3/LuaSnip" },
        { config = ev "require[[my.plugins/nvim-cmp]]",
            dependencies = { "hrsh7th/cmp-buffer", "hrsh7th/cmp-path", "hrsh7th/cmp-nvim-lsp", "hrsh7th/cmp-calc",
                "hrsh7th/cmp-nvim-lua", "hrsh7th/cmp-emoji", "onsails/lspkind-nvim", "saadparwaiz1/cmp_luasnip",
                "L3MON4D3/LuaSnip" }, "hrsh7th/nvim-cmp" },
        { init = function() vim.g.suda_smart_edit = 1 end, "lambdalisue/suda.vim" },
        { cmd = "Codi", config = ev "require[[my.plugins/codi]]", "metakirby5/codi.vim" },
        { ft = { "markdown", "org", "orgagenda" }, "dhruvasagar/vim-table-mode" },
        { config = function() require [[my.plugins/lualine]] end, "nvim-lualine/lualine.nvim" },
        { ft = { "fennel", "clojure" }, "Olical/conjure" },
        { config = ev "require[[my.plugins/fzf-lua]]",
            dependencies = { "vijaymarupudi/nvim-fzf", "kyazdani42/nvim-web-devicons" }, "ibhagwan/fzf-lua" },
        { lazy = false, priority = 1000,
            config = function() require('kanagawa').setup(); vim.cmd('colorscheme kanagawa') end, "rebelot/kanagawa.nvim" },
        { cmd = "Z", "nanotee/zoxide.vim" },
        {"stevearc/oil.nvim", config=true},
        { cmd = "StartupTime", "tweekmonster/startuptime.vim" },
        -- "rktjmp/hotpot.nvim",
        { config = { routes = { { view = 'split', filter = { min_width = 500 }, }, }, }, event = "VimEnter",
            dependencies = { "MunifTanjim/nui.nvim" }, "folke/noice.nvim" },

    })
